(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HackCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const stages=['Registered','Idea Screening','Mentoring','Submitted','Evaluation','Finalist'];
function uid(prefix='P'){return prefix+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,5).toUpperCase()}
function register(state,input){const name=(input.teamName||'').trim(),title=(input.projectTitle||'').trim(),members=(input.members||'').split(',').map(x=>x.trim()).filter(Boolean);if(!name||!title||members.length<2)throw new Error('Team name, project title and at least two comma-separated members are required.');if(state.projects.some(x=>x.teamName.toLowerCase()===name.toLowerCase()))throw new Error('Team name already exists.');const p={id:uid(),teamName:name,projectTitle:title,theme:input.theme||'Open Innovation',members,stage:'Registered',status:'Active',submissionUrl:'',progress:'Team registered',mentorFeedback:[],evaluation:null,createdAt:new Date().toISOString()};return{...state,projects:[...state.projects,p]}}
function update(state,id,changes){return{...state,projects:state.projects.map(p=>p.id===id?{...p,...changes}:p)}}
function mentor(state,id,feedback){if(!feedback.trim())throw new Error('Mentor feedback is required.');const p=state.projects.find(x=>x.id===id);if(!p)throw new Error('Project not found.');return update(state,id,{stage:p.stage==='Registered'?'Mentoring':p.stage,mentorFeedback:[...p.mentorFeedback,{text:feedback.trim(),at:new Date().toISOString()}]})}
function evaluate(state,id,scores,remarks=''){const vals=Object.values(scores).map(Number);if(vals.length!==4||vals.some(x=>x<0||x>25||!Number.isFinite(x)))throw new Error('Each criterion must be between 0 and 25.');return update(state,id,{stage:'Evaluation',evaluation:{scores,total:vals.reduce((a,b)=>a+b,0),remarks,at:new Date().toISOString()}})}
function metrics(state){const evaluated=state.projects.filter(x=>x.evaluation),avg=evaluated.length?evaluated.reduce((a,b)=>a+b.evaluation.total,0)/evaluated.length:0;return{teams:state.projects.length,participants:state.projects.reduce((a,b)=>a+b.members.length,0),submitted:state.projects.filter(x=>['Submitted','Evaluation','Finalist'].includes(x.stage)).length,evaluated:evaluated.length,averageScore:Number(avg.toFixed(1)),stageCounts:Object.fromEntries(stages.map(s=>[s,state.projects.filter(x=>x.stage===s).length]))}}
const demo=()=>({version:1,demo:true,projects:[{id:'DEMO-01',teamName:'Team Aster (Synthetic Demo)',projectTitle:'Accessible Campus Navigation',theme:'Accessibility',members:['Demo Member 1','Demo Member 2','Demo Member 3'],stage:'Mentoring',status:'Active',submissionUrl:'https://example.org/demo-aster',progress:'Clickable route-planning prototype completed.',mentorFeedback:[{text:'Add an offline fallback and document accessibility testing.',at:'2026-08-27T00:00:00Z'}],evaluation:null,createdAt:'2026-08-27T00:00:00Z'},{id:'DEMO-02',teamName:'Team Nova (Synthetic Demo)',projectTitle:'Energy-Aware Lab Scheduler',theme:'Sustainability',members:['Demo Member 4','Demo Member 5'],stage:'Evaluation',status:'Active',submissionUrl:'https://example.org/demo-nova',progress:'Scheduling model and dashboard submitted.',mentorFeedback:[{text:'Clarify the baseline used for energy savings.',at:'2026-08-27T00:00:00Z'}],evaluation:{scores:{innovation:21,technical:20,impact:22,presentation:19},total:82,remarks:'Strong demonstrator with a clearly bounded evaluation claim.',at:'2026-08-27T00:00:00Z'},createdAt:'2026-08-27T00:00:00Z'}]});
return{stages,register,update,mentor,evaluate,metrics,demo};});
